---
- name: Configure /etc/systemd/journald.conf
  copy:
    src: journald.conf
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart systemd-journald
